{{- if $.Values.github.secret.name }}
{{- if eq $.Values.github.secret.type "external-secret" }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
    name: prism-{{ $.Values.service.mode }}-{{ $.Values.service.name }}
spec:
  backendType: {{ $.Values.github.secret.backend }}
  {{- if $.Values.github.secret.role }}
  roleArn: {{ $.Values.github.secret.role }}
  {{- end }}
  {{- if $.Values.github.secret.region }}
  region: {{ $.Values.github.secret.region }}
  {{- end }}
  data:
    - key: {{ $.Values.github.secret.name }}
      name: key
{{- end }}
{{- end }}

